### ISSUE TITLE
Save loading bugs.

### ISSUE THREAD

**Issue by Animelici804** [HouJunhao33/undertale_engine#1]
I saved the game, but when I ran the game again, the save didn't load except the second and minutes and the room name while interacting to the savepoint object.

**Comment by Animelici804** [comment]
Also there's no intro (story) object. I mean this: https://www.youtube.com/watch?v=zs0QqiTAg28&t=1s

**Comment by Animelici804** [comment]
And there's also nothing in the settings menu.

**Comment by JasonCreeper** [comment]
These are all because TML(or HouJunhao33) doesn't finish it.This's a Pre-Releases(maybe?).

**Comment by HouJunhao33** [comment]
This is a pre-release version (see gamejolt), I'm working on it, please be patient and wait for the update.
(PS: I can only use the computer on weekends, so it might be slow.)

**Comment by Animelici804** [comment]
Okay, thanks.
